
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 29 15:45:49 CEST 2017
//----------------------------------------------------

package com.unitrier.st.uap;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 22;
  public static final int LT = 21;
  public static final int ELSE = 6;
  public static final int OR = 23;
  public static final int THEN = 5;
  public static final int SEMI = 24;
  public static final int IN = 3;
  public static final int WHILE = 8;
  public static final int RBRA = 12;
  public static final int IF = 4;
  public static final int LBRA = 11;
  public static final int GT = 20;
  public static final int ID = 26;
  public static final int SUB = 15;
  public static final int DO = 7;
  public static final int COMMA = 25;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int DIV = 17;
  public static final int ADD = 14;
  public static final int CONST = 27;
  public static final int error = 1;
  public static final int LET = 2;
  public static final int EQ = 18;
  public static final int ASSIGN = 13;
  public static final int RPAR = 10;
  public static final int NEQ = 19;
  public static final int LPAR = 9;
}

